# Generated by Django 2.2.14 on 2020-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('icon', models.TextField(blank=True, default=None, null=True)),
                ('country', models.TextField(blank=True, default=None, null=True)),
                ('city_name', models.TextField(blank=True, default=None, null=True)),
                ('weather_description', models.TextField(blank=True, default=None, null=True)),
                ('record_id', models.IntegerField(default=0)),
                ('wind', models.IntegerField(default=0)),
                ('clouds', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('temperature_from', models.FloatField(default=0)),
                ('temperature_to', models.FloatField(default=0)),
            ],
        ),
    ]
